<?php

/**
 * @package     Triangle Web
 * @link        https://github.com/Triangle-org
 *
 * @copyright   2018-2023 Localzet Group
 * @license     https://mit-license.org MIT
 */

use localzet\Server;

?>

<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
    <base href=""/>
    <title>Triangle Web</title>
    <meta charset="utf-8"/>

    <!-- About App -->
    <meta name="language" content="RU"/>
    <meta name="robots" content="noindex,nofollow"/>

    <!-- About System -->
    <meta name="generator" content="Triangle Framework"/>
    <meta name="server" version="Localzet Server <?= Server::getVersion() ?? '' ?>"/>

    <!-- Cache&Content -->
    <meta http-equiv="Expires" content="60"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <!-- SEO -->
    <link rel="shortcut icon" type="image/svg+xml" href="//cdn.localzet.com/public/media/localzet.svg"/>

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#12121200">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900"/>

</head>

<body>
<br/>
<center>
    <h1>
        <?php $print = $error ?? $data ?? 'Ошибка'; ?>
        <?= is_string($print) ? $print : print_r($print, true) ?>
    </h1>
</center>
<hr/>
<center>
    <a href="https://github.com/localzet/server" style="text-decoration: auto;">Localzet
        Server <?= Server::getVersion() ?? '' ?></a>
</center>
</body>

</html>